development:
  host: localhost
  database: bridgeport_development

test:
  host: localhost
  database: bridgeport_test

# set these environment variables on your prod server
production:
  host: production.saugususd.org
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  database: bridgeport_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
